# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d9f60b855b21de85d84b8235104936488f4e0790f6de1e2289ca8d4a7369d63be963cf4dcd37e9b7fcec3229ff57c13facde57020d05c28bb4d0441bb0228d

test:
  secret_key_base: f8b14eacad0d175e07c8281b025eb08479fbef57d66b23cc6ddb4e933382dd24cf56988b95e321e5871fa061fc9c302ecc63a9a2d137cb556d8825e7f0f9f538

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
